import {escapeHTML as esc,money,compactMoney,safeImage,filterPosts,validateText,validateImage,relativeTime} from './model.js';
import {DemoAPI} from './demo.js';
import {LiveAPI} from './api.js';
const config=window.RUSH_CONFIG;
const demo=config.mode!=='live';
const api=demo?new DemoAPI():new LiveAPI(config);
const $=s=>document.querySelector(s);
const icons={home:'<path d="m3 10 9-7 9 7v10H3Z"/><path d="M9 20v-7h6v7"/>',chart:'<path d="M3 3v18h18M6 15l5-5 4 3 6-8"/>',trophy:'<path d="M8 3h8v7a4 4 0 0 1-8 0ZM8 5H4v3a4 4 0 0 0 4 4m8-7h4v3a4 4 0 0 1-4 4M12 14v7m-4 0h8"/>',bookmark:'<path d="M6 3h12v18l-6-4-6 4Z"/>',user:'<circle cx="12" cy="8" r="4"/><path d="M4 21v-2a8 8 0 0 1 16 0v2"/>',search:'<circle cx="10" cy="10" r="7"/><path d="m15 15 6 6"/>',heart:'<path d="M20.8 4.6a5.5 5.5 0 0 0-7.8 0L12 5.7l-1.1-1.1a5.5 5.5 0 0 0-7.8 7.8L12 21l8.8-8.6a5.5 5.5 0 0 0 0-7.8Z"/>',comment:'<path d="M21 11.5a9 9 0 0 1-9 9 10 10 0 0 1-4-.9L3 21l1.4-5a9 9 0 1 1 16.6-4.5Z"/>',share:'<path d="M12 16V3m-4 4 4-4 4 4M5 12v9h14v-9"/>',image:'<rect x="3" y="3" width="18" height="18" rx="3"/><circle cx="8" cy="8" r="1"/><path d="m3 17 5-5 4 4 4-6 5 7"/>',bolt:'<path d="m13 2-9 12h7l-1 8 10-13h-7Z"/>',arrow:'<path d="M5 19 19 5M5 5h14v14"/>'};
const icon=name=>`<svg viewBox="0 0 24 24" aria-hidden="true">${icons[name]||icons.arrow}</svg>`;
document.querySelectorAll('[data-icon]').forEach(el=>el.innerHTML=icon(el.dataset.icon));
let me=null,posts=[],board={top:[]},view='home',filter='all',query='',sort='latest',selectedImage=null,page=0,hasMore=false,loading=false;
let bookmarks=[];try{bookmarks=JSON.parse(localStorage.getItem('rush.bookmarks'))||[];}catch{}
let toastTimer;
function toast(text){$('#toast').textContent=text;$('#toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').hidden=true,4500);}
function avatar(person={},large=false){const name=person.display_name||person.name||'?';const src=safeImage(person.avatar_url||'');return `<span class="avatar ${esc(person.color||'')} ${large?'large':''}">${src?`<img src="${src}" alt="${esc(name)}’s profile picture" loading="lazy">`:esc(name.split(/[ _]+/).map(s=>s[0]).slice(0,2).join('').toUpperCase())}</span>`;}
function nameButton(p){return `<button class="author" data-person="${esc(p.name)}">${esc(p.display_name||p.name)} <span class="verified" title="Market Rush player">✳</span></button>`;}
function openModal(content){$('#modal-content').innerHTML=content;if(!$('#modal').open)$('#modal').showModal();}
$('#close-modal').onclick=()=>$('#modal').close();$('#modal').addEventListener('click',e=>{if(e.target===$('#modal')){const r=$('#modal').getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)$('#modal').close();}});
function setTheme(theme){document.documentElement.dataset.theme=theme;try{localStorage.setItem('rush.theme',theme);}catch{}document.querySelectorAll('[data-theme-choice]').forEach(b=>{b.classList.toggle('chosen',b.dataset.themeChoice===theme);b.setAttribute('aria-pressed',b.dataset.themeChoice===theme);});}
setTheme(document.documentElement.dataset.theme||'dark');
document.querySelectorAll('[data-theme-choice]').forEach(b=>b.onclick=()=>setTheme(b.dataset.themeChoice));
function requireAccount(){if(me)return true;showLogin();return false;}
function showLogin(){openModal(`<span class="eyebrow">ONE ACCOUNT. THE WHOLE UNIVERSE.</span><h2 style="margin-top:12px">Welcome to Rush Social.</h2><p>Sign in with the email and password you already use for Market Rush.${demo?' Live login becomes available after the owner configures live mode and installs the database migration. This preview stays in demo mode.':''}</p>${demo?'<button id="return-demo" class="primary">Keep exploring the demo</button>':`<form id="login-form"><label class="form-label">Market Rush email<input name="email" type="email" autocomplete="username" required></label><label class="form-label">Password<input name="password" type="password" autocomplete="current-password" required></label><div class="form-error" id="login-error" role="alert"></div><button class="primary" type="submit">Sign in to Rush Social ↗</button></form>`}`);if(demo){$('#return-demo').onclick=()=>$('#modal').close();return;}$('#login-form').onsubmit=async e=>{e.preventDefault();const b=e.target.querySelector('button');b.disabled=true;try{me=await api.signIn(e.target.email.value,e.target.password.value);await reload();$('#modal').close();$('#connection').textContent='Connected · refreshes every 15s';}catch(err){$('#login-error').textContent=err.message;}finally{b.disabled=false;}};}
$('#connect').onclick=showLogin;
$('#mobile-theme').onclick=()=>setTheme(document.documentElement.dataset.theme==='dark'?'light':'dark');
function renderComposer(){const p=me||{name:'You'};$('#composer').innerHTML=`<form id="post-form"><div class="compose-top">${avatar(p)}<textarea id="post-text" name="body" maxlength="1000" placeholder="What’s the market saying, ${esc(me?.display_name?.split(' ')[0]||me?.name||'trader')}?" aria-label="Post text" required></textarea></div><div class="attachment" id="attachment" hidden></div><div class="compose-bottom"><label class="text-tool" tabindex="0">${icon('image')} Photo<input id="post-image" type="file" accept="image/jpeg,image/png,image/webp" class="sr-only"></label><select id="post-kind" aria-label="Post category"><option value="post">Thought</option><option value="banter">Banter</option></select><span id="post-count" class="count">0 / 1000</span><button type="submit" class="primary">Post ↗</button></div></form>`;
$('#post-text').oninput=e=>$('#post-count').textContent=`${e.target.value.length} / 1000`;
$('#post-image').onchange=e=>{try{selectedImage=validateImage(e.target.files[0]);$('#attachment').hidden=false;$('#attachment').innerHTML=`${esc(selectedImage.name)} <button type="button" id="remove-image" aria-label="Remove photo">×</button>`;$('#remove-image').onclick=()=>{selectedImage=null;e.target.value='';$('#attachment').hidden=true;};}catch(err){e.target.value='';toast(err.message);}};
$('#post-form').onsubmit=async e=>{e.preventDefault();if(!requireAccount())return;const b=e.target.querySelector('[type=submit]');b.disabled=true;try{const body=validateText($('#post-text').value);const url=selectedImage?await api.upload(selectedImage):null;await api.post(body,$('#post-kind').value,url);selectedImage=null;renderComposer();await refreshFeed();toast(demo?'Posted to your local demo.':'Shared with your trading circle.');}catch(err){toast(err.message);}finally{b.disabled=false;}};}
function tradeCard(t){if(!t)return '';const profit=t.pnl!=null;const positive=Number(t.pnl)>=0;return `<div class="trade-card"><div class="card-top"><span class="ticker-name"><span class="ticker-logo">${esc(t.symbol.slice(0,2))}</span>$${esc(t.symbol)}</span><span class="trade-kind">${esc(t.side==='SELL'?'SOLD POSITION':'BOUGHT POSITION')}</span></div><div class="trade-grid"><div><small>TOTAL VALUE</small><b>${money(t.total??t.shares*t.price)}</b></div><div><small>${profit?'REALIZED P/L':'SHARES BOUGHT'}</small><b class="${profit?(positive?'positive':'negative'):''}">${profit?`${positive?'+':''}${money(t.pnl)}`:esc(t.shares)}</b></div></div><div class="trade-detail"><span>${esc(t.shares)} shares</span><span>@ ${money(t.price)}</span><span>${t.pnlPct!=null?`${Number(t.pnlPct)>0?'+':''}${Number(t.pnlPct).toFixed(2)}% return`:'Market Rush'}</span></div></div>`;}
function postHTML(p){const a=p.author||{name:'trader'};return `<article class="post" id="post-${esc(p.id)}"><div class="post-head"><button class="icon-button" data-person="${esc(a.name)}" aria-label="View ${esc(a.name)}’s profile">${avatar(a)}</button><div>${nameButton(a)}<div class="post-meta"><span>@${esc(a.name)}</span><span>·</span><time datetime="${esc(p.created_at)}">${relativeTime(p.created_at)}</time>${p.kind==='banter'?'<span>· Banter</span>':''}</div></div>${p.author_id===me?.id&&p.kind!=='trade'?`<button class="icon-button" data-delete="${esc(p.id)}" aria-label="Delete post">×</button>`:''}</div><div class="post-content">${p.kind==='trade'?`<div class="trade-auto">${icon('bolt')} Automatically shared from Market Rush</div>`:''}${p.body?`<p class="post-body">${esc(p.body).replace(/\$([A-Z]{1,6})\b/g,'<span class="cashtag">$$$1</span>')}</p>`:''}${tradeCard(p.trade)}${p.meme?'<div class="meme"><div class="meme-top">my last two brain cells deciding what to buy</div><div class="meme-art" role="img" aria-label="A brain and a rocket: risk management versus the group chat">🧠 🚀</div></div>':''}${safeImage(p.image_url||'')?`<img class="post-image" src="${safeImage(p.image_url)}" alt="Photo shared by ${esc(a.display_name||a.name)}" loading="lazy">`:''}<div class="post-actions"><button data-like="${esc(p.id)}" class="${p.liked?'on':''}" aria-label="Like post" aria-pressed="${!!p.liked}">${icon('heart')} ${p.likes||0}</button><button data-comments="${esc(p.id)}" aria-label="Open comments">${icon('comment')} ${p.comment_count??p.comments?.length??0}</button><button data-share="${esc(p.id)}" aria-label="Copy post link">${icon('share')}</button><button data-bookmark="${esc(p.id)}" class="${bookmarks.includes(p.id)?'on':''}" aria-label="Bookmark post" aria-pressed="${bookmarks.includes(p.id)}">${icon('bookmark')}</button></div></div></article>`;}
function profileHTML(p,editable=false){return `<section class="profile-card"><div class="profile-cover"></div><div class="profile-info"><div class="profile-top">${avatar(p,true)}${editable?'<span><button class="secondary" id="edit-profile">Edit profile</button> <button class="secondary" id="profile-settings" aria-label="Account settings">⚙</button></span>':''}</div><h2>${esc(p.display_name||p.name)}</h2><div class="handle">@${esc(p.name)}</div><p class="bio">${esc(p.bio||'Making moves on Market Rush.')}</p><div class="profile-numbers"><div><small>NET WORTH</small><b>${money(p.worth)}</b></div><div><small>AVAILABLE CASH</small><b>${money(p.cash)}</b></div><div><small>GLOBAL RANK</small><b class="positive">${p.rank?'#'+esc(p.rank):'—'}</b></div></div></div></section>`;}
function renderContent(){if(view==='leaderboard'){$('#content').innerHTML=`<div class="empty"><h3>The bragging rights board</h3><p>Ranked by net worth in Market Rush.</p></div>${board.top.length?board.top.map(p=>`<div class="panel">${leaderHTML(p)}</div>`).join(''):'<div class="empty">No ranked traders yet.</div>'}`;return;}
const visible=filterPosts(posts,{filter: view==='trades'?'trades':filter,view,query,sort,bookmarks,userId:me?.id});$('#content').innerHTML=(view==='profile'&&me?profileHTML(me,true):'')+(visible.length?visible.map(postHTML).join(''):`<div class="empty"><h3>${view==='bookmarks'?'Keep the good ones.':'Nothing here just yet.'}</h3><p>${view==='bookmarks'?'Tap the bookmark on a post to save it on this device.':query?'Try another search.':'Share a thought, a win, or a very questionable take.'}</p></div>`);$('#load-more').hidden=!hasMore;if($('#edit-profile'))$('#edit-profile').onclick=editProfile;if($('#profile-settings'))$('#profile-settings').onclick=accountMenu;
const target=location.hash.slice(1);if(target&&document.getElementById(target))document.getElementById(target).scrollIntoView({block:'center'});}
function leaderHTML(p){return `<button class="leader" data-person="${esc(p.name)}"><span class="rank">${esc(p.rank)}</span>${avatar(p)}<span class="leader-name">${esc(p.display_name||p.name)}<small>@${esc(p.name)}</small></span><span class="leader-worth">${compactMoney(p.worth)}</span></button>`;}
function renderSidebars(){const p=me||{};$('#account').innerHTML=me?`<button class="account" id="account-button">${avatar(p)}<span><b>${esc(p.display_name||p.name)}</b><small>@${esc(p.name)}</small></span><span class="more">···</span></button>`:'<button class="primary" id="login-button">Sign in with Market Rush</button>';if($('#account-button'))$('#account-button').onclick=accountMenu;if($('#login-button'))$('#login-button').onclick=showLogin;
$('#portfolio').innerHTML=`<div class="panel-heading"><span class="eyebrow">YOUR MARKET RUSH PORTFOLIO</span>${icon('arrow')}</div><div class="portfolio-value">${money(p.worth)}</div><p class="portfolio-sub">${demo?'Example net worth · demo data':'Net worth · virtual USD'}</p>${demo?'<svg class="sparkline" viewBox="0 0 240 55" aria-hidden="true"><path d="M0 48 16 41 27 46 45 31 58 36 78 25 93 30 111 17 131 24 149 10 167 18 188 9 207 15 223 4 240 1"/></svg>':'<div style="height:18px"></div>'}<div class="portfolio-stats"><div><small>Global rank</small><b class="rank-pill">${p.rank?'#'+esc(p.rank):'—'} <span style="color:var(--muted)">/ ${esc(board.players??'—')}</span></b></div><div><small>Available cash</small><b>${compactMoney(p.cash)}</b></div></div>${config.marketRushUrl?`<a class="game-link" href="${esc(validGameUrl())}" target="_blank" rel="noopener noreferrer">Open Market Rush ${icon('arrow')}</a>`:'<div class="game-link">Market Rush linked account <span>↗</span></div>'}`;
$('#leaders').innerHTML=`<div class="panel-heading"><h3>Top of the game</h3>${icon('trophy')}</div>${board.top.slice(0,5).map(leaderHTML).join('')||'<p class="fine">Sign in to see the leaderboard.</p>'}<button class="panel-more" data-view="leaderboard">View full leaderboard ↗</button>`;
const counts={};for(const p of posts){if(p.trade)counts[p.trade.symbol]=(counts[p.trade.symbol]||0)+1;for(const t of p.body?.match(/\$[A-Z]{1,6}\b/g)||[])counts[t.slice(1)]=(counts[t.slice(1)]||0)+1;}
$('#trending').innerHTML=`<div class="panel-heading"><h3>On the radar</h3><span class="eyebrow">THIS FEED</span></div>${Object.entries(counts).sort((a,b)=>b[1]-a[1]).slice(0,3).map(([symbol,n])=>`<button class="trend" data-ticker="${esc(symbol)}"><span><b>$${esc(symbol)}</b><small>${n} ${n===1?'mention':'mentions'} in loaded posts</small></span><span>↗</span></button>`).join('')||'<p class="fine">Tickers appear as your circle shares.</p>'}`;}
function validGameUrl(){try{const u=new URL(config.marketRushUrl);return ['https:','http:'].includes(u.protocol)?u.href:'#';}catch{return '#';}}
function navigate(next){if(next==='profile'&&!requireAccount())return;view=next;filter=next==='trades'?'trades':'all';query='';$('#search').value='';document.querySelectorAll('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.view===view));$('#page-title').innerHTML=({home:'The feed',trades:'Trade tape',leaderboard:'Leaderboard',bookmarks:'Saved for later',profile:'Your profile'}[view]||'The feed')+'<span class="lime">.</span>';$('#hero').hidden=view!=='home';$('#composer').hidden=!['home','trades'].includes(view);$('#feed-controls').hidden=view==='leaderboard';document.querySelectorAll('[data-filter]').forEach(b=>{b.classList.toggle('selected',b.dataset.filter===filter);b.setAttribute('aria-selected',b.dataset.filter===filter);});renderContent();window.scrollTo({top:0});}
function focusCompose(){navigate('home');$('#post-text').focus();$('#composer').scrollIntoView({behavior:'smooth',block:'center'});}
$('#compose-nav').onclick=focusCompose;$('#hero-post').onclick=focusCompose;
$('#sort').onchange=e=>{sort=e.target.value;renderContent();};$('#search').oninput=e=>{query=e.target.value;if(view==='leaderboard')view='home';renderContent();};
async function refreshFeed(){const incoming=await api.feed(0);posts=incoming;page=0;hasMore=incoming.length===30;renderContent();renderSidebars();}
async function reload(){const result=await Promise.all([api.feed(0),api.leaderboard(),me?api.profile(me.name):Promise.resolve(null)]);posts=result[0];board=result[1];if(result[2])me=result[2];page=0;hasMore=posts.length===30;renderComposer();renderContent();renderSidebars();}
$('#load-more').onclick=async()=>{if(loading)return;loading=true;$('#load-more').disabled=true;try{const next=await api.feed((page+1)*30);page++;hasMore=next.length===30;const ids=new Set(posts.map(p=>p.id));posts.push(...next.filter(p=>!ids.has(p.id)));renderContent();}catch(err){toast(err.message);}finally{loading=false;$('#load-more').disabled=false;}};
async function showProfile(name){openModal('<p>Loading trader profile…</p>');try{const p=await api.profile(name);if(!p)throw Error('This profile is unavailable.');$('#modal-content').innerHTML=profileHTML(p,p.id===me?.id);if($('#edit-profile'))$('#edit-profile').onclick=editProfile;if($('#profile-settings'))$('#profile-settings').onclick=accountMenu;}catch(err){$('#modal-content').innerHTML=`<p>${esc(err.message)}</p>`;}}
function accountMenu(){openModal(`<h2>Your corner of Rush.</h2><p>Signed in as @${esc(me.name)}${demo?' · local demo':''}</p><div class="theme-options"><button id="modal-light">☀ Light mode</button><button id="modal-dark">☾ Dark mode</button></div><div class="modal-actions"><button class="secondary" id="modal-edit">Edit profile</button><button class="secondary" id="logout">${demo?'About demo':'Sign out'}</button></div>`);$('#modal-light').onclick=()=>setTheme('light');$('#modal-dark').onclick=()=>setTheme('dark');$('#modal-edit').onclick=editProfile;$('#logout').onclick=async()=>{if(demo){showLogin();return;}await api.signOut();me=null;posts=[];board={top:[]};$('#modal').close();renderComposer();renderSidebars();renderContent();showLogin();};}
function editProfile(){openModal(`<h2>Make it yours.</h2><p>Your trading name, cash, and rank come from Market Rush.</p><form id="profile-form"><label class="form-label">Display name<input name="display_name" maxlength="40" value="${esc(me.display_name||me.name)}" required></label><label class="form-label">Bio<textarea name="bio" maxlength="160">${esc(me.bio||'')}</textarea></label><label class="form-label">Profile photo · JPG, PNG, WebP · up to 5 MB<input name="avatar" type="file" accept="image/jpeg,image/png,image/webp"></label><div class="form-error" id="profile-error" role="alert"></div><div class="modal-actions"><button class="secondary" type="button" id="remove-avatar">Remove photo</button><button class="primary" type="submit">Save profile</button></div></form>`);let remove=false;$('#remove-avatar').onclick=()=>{remove=true;toast('Photo will be removed when you save.');};$('#profile-form').onsubmit=async e=>{e.preventDefault();const b=e.target.querySelector('[type=submit]');b.disabled=true;try{const file=e.target.avatar.files[0];const avatar_url=file?await api.upload(validateImage(file),'avatars'):remove?null:me.avatar_url;const values={display_name:validateText(e.target.display_name.value,40),bio:e.target.bio.value.trim(),avatar_url};await api.updateProfile(values);Object.assign(me,values);await reload();$('#modal').close();toast('Profile updated.');}catch(err){$('#profile-error').textContent=err.message;}finally{b.disabled=false;}};}
async function comments(id){openModal('<h2>The conversation</h2><p>Loading comments…</p>');try{const items=await api.comments(id);$('#modal-content').innerHTML=`<h2>The conversation</h2><div class="comment-list">${items.length?items.map(c=>`<div class="comment">${avatar(c.author)}<div><b>${esc(c.author?.display_name||c.author?.name)}</b><p>${esc(c.body)}</p><small>${relativeTime(c.created_at)}</small></div></div>`).join(''):'<p>No replies yet. Be the first.</p>'}</div><form class="comment-form" id="comment-form"><input name="body" placeholder="Add to the conversation…" maxlength="500" aria-label="Comment" required><button class="primary">Reply</button></form><div id="comment-error" class="form-error" role="alert"></div>`;$('#comment-form').onsubmit=async e=>{e.preventDefault();if(!requireAccount())return;const b=e.target.querySelector('button');b.disabled=true;try{await api.comment(id,validateText(e.target.body.value,500));await refreshFeed();await comments(id);}catch(err){$('#comment-error').textContent=err.message;}finally{b.disabled=false;}};}catch(err){$('#modal-content').innerHTML=`<h2>The conversation</h2><p>${esc(err.message)}</p>`;}}
document.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b)return;try{if(b.dataset.view)navigate(b.dataset.view);if(b.dataset.filter){if(view==='trades')navigate('home');filter=b.dataset.filter;document.querySelectorAll('[data-filter]').forEach(t=>{t.classList.toggle('selected',t===b);t.setAttribute('aria-selected',t===b);});renderContent();}if(b.dataset.person)await showProfile(b.dataset.person);if(b.dataset.ticker){navigate('home');query=b.dataset.ticker;$('#search').value=query;renderContent();}if(b.dataset.like&&requireAccount()){b.disabled=true;await api.like(b.dataset.like);await refreshFeed();}if(b.dataset.comments)await comments(b.dataset.comments);if(b.dataset.bookmark){const id=b.dataset.bookmark;bookmarks=bookmarks.includes(id)?bookmarks.filter(x=>x!==id):[...bookmarks,id];localStorage.setItem('rush.bookmarks',JSON.stringify(bookmarks));renderContent();}if(b.dataset.share){await navigator.clipboard.writeText(`${location.href.split('#')[0]}#post-${b.dataset.share}`);toast('Post link copied.');}if(b.dataset.delete){openModal('<h2>Delete your post?</h2><p>This removes it and its replies from the feed.</p><div class="modal-actions"><button class="secondary" id="cancel-delete">Keep post</button><button class="primary" id="confirm-delete">Delete post</button></div>');$('#cancel-delete').onclick=()=>$('#modal').close();$('#confirm-delete').onclick=async()=>{try{await api.deletePost(b.dataset.delete);$('#modal').close();await refreshFeed();toast('Post deleted.');}catch(err){toast(err.message);}};}}catch(err){toast(err.message);}finally{b.disabled=false;}});
$('#demo-banner').hidden=!demo;$('#connection').textContent=demo?'Demo playground':'Connecting';
async function start(){try{me=await api.init();renderComposer();renderSidebars();if(!me&&!demo){$('#content').innerHTML='<div class="empty"><h3>Your circle is waiting.</h3><p>Sign in with your Market Rush account to join the feed.</p><button class="primary" id="feed-login">Sign in</button></div>';$('#feed-login').onclick=showLogin;$('#connection').textContent='Sign in to connect';return;}await reload();$('#connection').textContent=demo?'Demo playground':'Connected · refreshes every 15s';}catch(err){renderComposer();renderSidebars();$('#connection').textContent='Connection needs attention';$('#content').innerHTML=`<div class="empty"><h3>Couldn’t connect yet.</h3><p>${esc(err.message)}</p><button id="retry" class="secondary">Try again</button></div>`;$('#retry').onclick=start;}}
await start();
if(!demo)setInterval(async()=>{if(document.hidden||!api.user||$('#modal').open||loading)return;loading=true;try{const [incoming,leaderboard,profile]=await Promise.all([api.feed(0),api.leaderboard(),api.profile(me.name)]);const ids=new Set(incoming.map(p=>p.id));posts=[...incoming,...posts.filter(p=>!ids.has(p.id))];board=leaderboard;me=profile;renderContent();renderSidebars();$('#connection').textContent='Connected · refreshes every 15s';}catch(err){$('#connection').textContent='Reconnecting';toast(err.message);}finally{loading=false;}},Math.max(15000,config.pollIntervalMs||15000));
