import { integer, sqliteTable, text, primaryKey, index } from 'drizzle-orm/sqlite-core';
export const users=sqliteTable('users',{id:text('id').primaryKey(),name:text('name').notNull(),bio:text('bio').notNull().default(''),avatarId:text('avatar_id'),worth:text('worth'),cash:text('cash'),rank:integer('rank'),updatedAt:integer('updated_at'),createdAt:integer('created_at').notNull()});
export const posts=sqliteTable('posts',{id:text('id').primaryKey(),userId:text('user_id').notNull().references(()=>users.id),author:text('author').notNull(),kind:text('kind').notNull(),content:text('content').notNull(),symbol:text('symbol'),tradeJson:text('trade_json'),imageId:text('image_id'),createdAt:integer('created_at').notNull()},t=>[index('posts_time_idx').on(t.createdAt)]);
export const likes=sqliteTable('likes',{postId:text('post_id').notNull().references(()=>posts.id,{onDelete:'cascade'}),userId:text('user_id').notNull().references(()=>users.id),createdAt:integer('created_at').notNull()},t=>[primaryKey({columns:[t.postId,t.userId]})]);
export const comments=sqliteTable('comments',{id:text('id').primaryKey(),postId:text('post_id').notNull().references(()=>posts.id,{onDelete:'cascade'}),userId:text('user_id').notNull().references(()=>users.id),author:text('author').notNull(),content:text('content').notNull(),createdAt:integer('created_at').notNull()},t=>[index('comments_post_idx').on(t.postId,t.createdAt)]);
export const uploads=sqliteTable('uploads',{id:text('id').primaryKey(),userId:text('user_id').notNull().references(()=>users.id),mime:text('mime').notNull(),createdAt:integer('created_at').notNull()});
export const tradeActivity=sqliteTable('trade_activity',{id:text('id').primaryKey(),trader:text('trader').notNull(),tradeId:text('trade_id').notNull(),symbol:text('symbol').notNull(),side:text('side').notNull(),shares:integer('shares').notNull(),price:text('price').notNull(),total:text('total').notNull(),pnl:text('pnl'),tradedAt:integer('traded_at').notNull(),observedAt:integer('observed_at').notNull()},t=>[index('activity_time_idx').on(t.tradedAt,t.id)]);
export const messages=sqliteTable('messages',{id:text('id').primaryKey(),senderId:text('sender_id').notNull().references(()=>users.id),recipientId:text('recipient_id').notNull().references(()=>users.id),content:text('content').notNull(),createdAt:integer('created_at').notNull(),readAt:integer('read_at')},t=>[index('messages_pair_idx').on(t.senderId,t.recipientId,t.createdAt)]);
export const syncState=sqliteTable('sync_state',{id:text('id').primaryKey(),lastSync:integer('last_sync').notNull().default(0),cursor:integer('cursor').notNull().default(0)});
