'use client';
import {ActivityPanel,MessagesPanel,ThemeControl} from './features';
import { useCallback,useEffect,useRef,useState } from 'react';
import { ArrowUpRight,BarChart3,Camera,ChartNoAxesCombined,Check,ChevronDown,Flame,Heart,Home,ImagePlus,LogOut,MessageCircle,Plus,RefreshCw,Send,Smile,Sparkles,TrendingUp,Trophy,User,X } from 'lucide-react';
const GAME_URL='https://hrdshcnqgmfrklnietny.supabase.co',KEY='sb_publishable_rF43LSkajxLcjkkSjhM5eQ_9_vPJu3Y';
const SYMBOLS=['AAPL','TSLA','NVDA','AMZN','MSFT','GOOGL','BRUMP','ZOEY'];
const money=(n:unknown)=>n!=null&&Number.isFinite(Number(n))?new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:2}).format(Number(n)):'—';
const short=(n:unknown)=>n!=null&&Number.isFinite(Number(n))?new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',notation:'compact',maximumFractionDigits:1}).format(Number(n)):'—';
const ago=(t:number)=>{const m=Math.max(0,Math.floor((Date.now()-t)/60000));return m<1?'just now':m<60?m+'m ago':m<1440?Math.floor(m/60)+'h ago':new Date(t).toLocaleDateString();};
type Session={access_token:string;refresh_token:string;expires_at:number};
type Profile={id?:string;name:string;avatar_id?:string;bio?:string;worth?:string|number;cash?:string|number;rank?:number;updated_at?:number};
type Post={id:string;user_id:string;author:string;author_name?:string;kind:string;content:string;symbol?:string;trade_json?:string;image_id?:string;avatar_id?:string;worth?:string;rank?:number;created_at:number;likes:number;comments:number;liked:number};
function Avatar({name,id,api,large=false}:{name:string;id?:string;api?:any;large?:boolean}){return <div className={'avatar '+(large?'large':'')} style={{'--hue':String([...name].reduce((a,c)=>a+c.charCodeAt(0),0)%360)} as any}>{id&&api?<PrivateImage id={id} api={api} alt={name+' profile picture'}/>:name.slice(0,2).toUpperCase()}</div>;}
function PrivateImage({id,api,alt}:{id:string;api:any;alt:string}){const [src,setSrc]=useState('');useEffect(()=>{let live=true,url='';api('/api/images/'+id,undefined,true).then((blob:Blob)=>{url=URL.createObjectURL(blob);if(live)setSrc(url);else URL.revokeObjectURL(url);}).catch(()=>{});return()=>{live=false;if(url)URL.revokeObjectURL(url);};},[id,api]);return src?<img src={src} alt={alt}/>:<span className="image-loading">Loading image…</span>;}
export default function HomePage(){
 const session=useRef<Session|null>(null),refreshPromise=useRef<Promise<void>|null>(null),feedSequence=useRef(0);
 const [signed,setSigned]=useState(false),[loginOpen,setLoginOpen]=useState(false),[profile,setProfile]=useState<Profile|null>(null),[view,setView]=useState('all'),[posts,setPosts]=useState<Post[]>([]),[next,setNext]=useState<number|null>(null),[loading,setLoading]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[totals,setTotals]=useState({posts:0,members:0}),[board,setBoard]=useState<any>(null),[trades,setTrades]=useState<any[]>([]),[modalProfile,setModalProfile]=useState<Profile|null>(null),[edit,setEdit]=useState(false),[bio,setBio]=useState(''),[avatarFile,setAvatarFile]=useState<File|null>(null),[busy,setBusy]=useState(false);
 const [kind,setKind]=useState('chat'),[content,setContent]=useState(''),[symbol,setSymbol]=useState(''),[tradeId,setTradeId]=useState(''),[file,setFile]=useState<File|null>(null),[preview,setPreview]=useState(''),[commentsFor,setCommentsFor]=useState<string|null>(null),[comments,setComments]=useState<any[]>([]),[reply,setReply]=useState(''),[search,setSearch]=useState('');
 const [messagesOpen,setMessagesOpen]=useState(false),[dmPeer,setDmPeer]=useState('');
 const compose=useRef<HTMLTextAreaElement>(null),fileInput=useRef<HTMLInputElement>(null);
 const api=useCallback(async(path:string,body?:any,image=false)=>{
  async function renew(){if(refreshPromise.current)return refreshPromise.current;const current=session.current;if(!current)throw Error('Sign in to continue.');refreshPromise.current=(async()=>{const r=await fetch(GAME_URL+'/auth/v1/token?grant_type=refresh_token',{method:'POST',headers:{apikey:KEY,'Content-Type':'application/json'},body:JSON.stringify({refresh_token:current.refresh_token}),signal:AbortSignal.timeout(12000)});const d:any=await r.json();if(!r.ok||!d.access_token)throw Error('Your game session expired. Sign in again.');if(session.current===current)session.current={...d,expires_at:Date.now()/1000+(d.expires_in||3600)};})().finally(()=>{refreshPromise.current=null;});return refreshPromise.current;}
  if(!session.current)throw Error('Sign in with MarketRush to continue.');if(session.current.expires_at<Date.now()/1000+60)await renew();
  const send=()=>{if(!session.current)throw Error('Sign in again.');return fetch(path,{method:body===undefined?'GET':'POST',headers:{Authorization:'Bearer '+session.current.access_token,...(body instanceof File?{'Content-Type':body.type}:{'Content-Type':'application/json'})},...(body===undefined?{}:{body:body instanceof File?body:JSON.stringify(body)}),signal:AbortSignal.timeout(20000)});};
  let r=await send();if(r.status===401){await renew();r=await send();}if(image&&r.ok)return r.blob();const d:any=await r.json();if(!r.ok)throw Error(d.error||'Please try again.');return d;
 },[]);
 const loadFeed=useCallback(async(append=false)=>{if(!session.current)return;const seq=++feedSequence.current;setLoading(true);try{const d=await api('/api/social?view='+(view==='activity'?'all':view)+(append&&next?'&before='+next:''));if(seq!==feedSequence.current||!session.current)return;setPosts(old=>append?[...old,...d.posts.filter((p:Post)=>!old.some(o=>o.id===p.id))]:d.posts);setNext(d.next);setTotals(d.totals||{posts:0,members:0});setError('');}catch(e:any){if(seq===feedSequence.current)setError(e.message);}finally{if(seq===feedSequence.current)setLoading(false);}},[api,view,next]);
 const updateAccount=useCallback(async()=>{const d=await api('/api/account');if(!session.current)return;setProfile(d.profile);setTrades(d.trades||[]);const b=await api('/api/leaderboard');if(session.current)setBoard(b);},[api]);
 useEffect(()=>{if(!signed)return;loadFeed();const timer=setInterval(()=>{updateAccount().catch(e=>setError(e.message));},30000);return()=>clearInterval(timer);},[signed,view]);
 useEffect(()=>{if(!signed)return;const timer=setInterval(()=>{if(!document.hidden&&next==null)loadFeed();},20000);return()=>clearInterval(timer);},[signed,loadFeed,next]);
 useEffect(()=>{if(!file){setPreview('');return;}const url=URL.createObjectURL(file);setPreview(url);return()=>URL.revokeObjectURL(url);},[file]);
 function needLogin(){if(!signed){setLoginOpen(true);return true;}return false;}
 async function login(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');const form=e.currentTarget,fd=new FormData(form);try{const r=await fetch(GAME_URL+'/auth/v1/token?grant_type=password',{method:'POST',headers:{apikey:KEY,'Content-Type':'application/json'},body:JSON.stringify({email:String(fd.get('email')).trim(),password:fd.get('password')}),signal:AbortSignal.timeout(15000)});const d:any=await r.json();(form.elements.namedItem('password') as HTMLInputElement).value='';if(!r.ok||!d.access_token)throw Error(d.error_description||d.message||'Could not sign in.');session.current={...d,expires_at:Date.now()/1000+(d.expires_in||3600)};await updateAccount();setSigned(true);setLoginOpen(false);setNotice('Welcome to the conversation.');}catch(e:any){session.current=null;setError(e.message);}finally{setBusy(false);}}
 function logout(){setMessagesOpen(false);setDmPeer('');session.current=null;feedSequence.current++;setSigned(false);setPosts([]);setProfile(null);setBoard(null);setTrades([]);setModalProfile(null);setEdit(false);setCommentsFor(null);setError('');setNotice('');setContent('');setFile(null);setTradeId('');setNext(null);}
 function validFile(f:File){if(!['image/jpeg','image/png','image/webp'].includes(f.type)||f.size>5*1024*1024){setError('Choose a JPEG, PNG, or WebP image under 5 MB.');return false;}return true;}
 async function publish(e:React.FormEvent){e.preventDefault();if(needLogin())return;setBusy(true);setError('');try{const image=file?await api('/api/uploads',file):null;await api('/api/social',{action:'create',kind,content,symbol:symbol||null,tradeId:tradeId||null,imageId:image?.id||null});setContent('');setFile(null);setTradeId('');setSymbol('');setNotice('Posted to the feed.');await loadFeed();}catch(e:any){setError(e.message);}finally{setBusy(false);}}
 async function like(p:Post){if(needLogin())return;try{await api('/api/social',{action:'like',postId:p.id,liked:!p.liked});setPosts(old=>old.map(o=>o.id===p.id?{...o,liked:p.liked?0:1,likes:o.likes+(p.liked?-1:1)}:o));}catch(e:any){setError(e.message);}}
 async function openComments(id:string){if(needLogin())return;setCommentsFor(id);setComments([]);setReply('');try{const d=await api('/api/comments?postId='+id);setComments(d.comments);}catch(e:any){setError(e.message);}}
 async function sendReply(e:React.FormEvent){e.preventDefault();setBusy(true);try{await api('/api/social',{action:'comment',postId:commentsFor,content:reply});setReply('');const d=await api('/api/comments?postId='+commentsFor);setComments(d.comments);setPosts(old=>old.map(p=>p.id===commentsFor?{...p,comments:p.comments+1}:p));}catch(e:any){setError(e.message);}finally{setBusy(false);}}
 async function openProfile(name:string){if(needLogin())return;setBusy(true);try{const d=await api('/api/account?name='+encodeURIComponent(name));setModalProfile(d.profile);}catch(e:any){setError(e.message);}finally{setBusy(false);}}
 async function saveProfile(e:React.FormEvent){e.preventDefault();setBusy(true);try{const image=avatarFile?await api('/api/uploads',avatarFile):null;await api('/api/account',{bio,avatarId:image?.id||profile?.avatar_id||null});await updateAccount();await loadFeed();setEdit(false);setAvatarFile(null);setNotice('Profile updated.');}catch(e:any){setError(e.message);}finally{setBusy(false);}}
 const visible=posts.filter(p=>!search||[p.content,p.author_name||p.author,p.symbol||''].join(' ').toLowerCase().includes(search.toLowerCase()));
 return <div className="app"><header className="topbar"><a className="brand" href="/" aria-label="Rush Social home"><span className="brand-mark"><ChartNoAxesCombined size={25}/></span><span>rush<span className="brand-light">social</span><sup>↗</sup></span></a><div className="top-label"><span className="live-dot"/> THE MARKET IS A GROUP CHAT</div><div className="top-actions"><ThemeControl/>{signed?<><button className="icon-button" aria-label="Refresh feed" onClick={()=>{loadFeed();updateAccount().catch(e=>setError(e.message));}}><RefreshCw size={18}/></button><button className="account-button" onClick={()=>profile&&openProfile(profile.name)}><Avatar name={profile?.name||'You'} id={profile?.avatar_id} api={api}/><span>{profile?.name}</span><ChevronDown size={14}/></button></>:<button className="primary small" onClick={()=>setLoginOpen(true)}>Sign in with MarketRush <ArrowUpRight size={15}/></button>}</div></header>
 <div className="shell"><aside className="sidebar"><p className="overline">YOUR CORNER OF THE MARKET</p><nav>{[{key:'all',name:'Home',Icon:Home},{key:'activity',name:'Market activity',Icon:BarChart3},{key:'trade',name:'Big trades',Icon:TrendingUp},{key:'joke',name:'For the laughs',Icon:Smile},{key:'mine',name:'My posts',Icon:User}].map(({key,name,Icon})=><button key={key} className={'nav-item '+(view===key?'active':'')} onClick={()=>{if(key==='mine'&&needLogin())return;setView(key);setNext(null);setSearch('');}}><Icon size={20}/>{name}{view===key&&<span className="nav-dot"/>}</button>)}<button className="nav-item" onClick={()=>{if(!needLogin()){setDmPeer('');setMessagesOpen(true);}}}><MessageCircle size={20}/>Messages</button></nav><button className="primary new-post" onClick={()=>{if(!needLogin())compose.current?.focus();}}><Plus size={19}/> New post</button><div className="sidebar-card"><span className="tiny-star">✳</span><h3>All the rush.<br/>None of the real money.</h3><p>Big wins, questionable moves, and the friends who were there for it.</p><span className="pill subtle">100% virtual. 100% a good time.</span></div><div className="sidebar-bottom">Made for MarketRush traders.<br/>Be cool. Keep it fictional.{signed&&<button onClick={logout}><LogOut size={15}/> Sign out</button>}</div></aside>
 <main className="main-feed"><section className="feed-heading"><p className="overline">WELCOME TO RUSH SOCIAL</p><h1>What's happening?</h1><p>Trades, takes, and your people. All in one place.</p></section>
 <div className="mobile-nav">{[['all','Home'],['activity','Activity'],['trade','Flexes'],['joke','Jokes']].map(([key,label])=><button key={key} className={view===key?'active':''} onClick={()=>{if(key==='mine'&&needLogin())return;setView(key);setNext(null);}}>{label}</button>)}<button onClick={()=>{if(!needLogin()){setDmPeer('');setMessagesOpen(true);}}}>DMs</button></div>
 {error&&<div className="message error" role="alert">{error}<button aria-label="Dismiss error" onClick={()=>setError('')}><X size={16}/></button></div>}{notice&&<div className="message success" role="status">{notice}<button aria-label="Dismiss notice" onClick={()=>setNotice('')}><X size={16}/></button></div>}
 {view!=='activity'&&<form className="composer" onSubmit={publish}><div className="composer-main"><Avatar name={profile?.name||'RS'} id={profile?.avatar_id} api={api}/><textarea ref={compose} value={content} onChange={e=>setContent(e.target.value)} maxLength={1200} placeholder={signed?'Big win? Terrible joke? The feed is yours.':'Your next big trade deserves an audience.'} aria-label="Write a post" onFocus={()=>{if(!signed)setLoginOpen(true);}}/></div>
 <div className="post-types">{[['chat','Just chatting'],['trade','Trade flex'],['joke','Market humor']].map(([v,label])=><button type="button" key={v} className={'type '+(kind===v?'selected':'')} onClick={()=>{setKind(v);if(v!=='trade')setTradeId('');}}>{label}</button>)}</div>
 {kind==='trade'&&signed&&<label className="receipt-picker">Attach a verified recent trade<select value={tradeId} onChange={e=>setTradeId(e.target.value)}><option value="">No receipt · text or screenshot only</option>{trades.map(t=><option key={t.id} value={String(t.id)}>{t.side} {t.shares} {t.symbol} · {money(t.total)}</option>)}</select><small>Receipts are checked against your game history when posted.</small></label>}
 {preview&&<div className="upload-preview"><img src={preview} alt="Screenshot to attach"/><button type="button" aria-label="Remove screenshot" onClick={()=>setFile(null)}><X size={16}/></button></div>}
 <div className="composer-bottom"><div className="composer-tools"><input ref={fileInput} type="file" accept="image/png,image/jpeg,image/webp" hidden onChange={e=>{const f=e.target.files?.[0];if(f&&validFile(f))setFile(f);e.target.value='';}}/><button type="button" className="tool-button" onClick={()=>{if(!needLogin())fileInput.current?.click();}}><ImagePlus size={18}/><span>Photo</span></button><select value={symbol} onChange={e=>setSymbol(e.target.value)} aria-label="Tag a stock"><option value="">$ Ticker</option>{SYMBOLS.map(s=><option key={s}>{s}</option>)}</select></div><div className="composer-submit"><span>{content.length}/1200</span><button className="primary small" disabled={busy||signed&&!(content.trim()||file||tradeId)}>{busy?'Working…':'Post'}<ArrowUpRight size={15}/></button></div></div></form>}
 {view==='activity'&&signed?<ActivityPanel api={api} openProfile={openProfile}/>:<><div className="feed-toolbar"><h2>{view==='all'?'On the feed':view==='trade'?'Big trades, bigger stories':view==='joke'?'For the laughs':'Your posts'}<span>{signed?totals.posts:'—'}</span></h2><input type="search" placeholder="Search loaded posts…" aria-label="Search loaded posts" value={search} onChange={e=>setSearch(e.target.value)}/></div>
 {!signed?<section className="join-card"><div className="join-icon"><MessageCircle size={28}/><Sparkles size={17}/></div><h2>Your people. Your market.</h2><p>Sign in with your existing MarketRush account to see the conversation, share a trade, and find out who’s on top.</p><button className="primary" onClick={()=>setLoginOpen(true)}>Join the conversation <ArrowUpRight size={17}/></button><small>No new account needed.</small></section>:<>{loading&&!posts.length?<div className="empty-state">Loading the conversation…</div>:!visible.length?<div className="empty-state"><Smile size={30}/><h3>{search?'No matching posts':'A fresh feed. Your move.'}</h3><p>{search?'Try another word or load more posts.':'Share the first trade, joke, or screenshot.'}</p></div>:visible.map(p=>{let trade:any=null;try{trade=p.trade_json?JSON.parse(p.trade_json):null;}catch{}return <article className="post" key={p.id}><div className="post-head"><button className="author-button" onClick={()=>openProfile(p.author_name||p.author)}><Avatar name={p.author_name||p.author} id={p.avatar_id} api={api}/><div><strong>{p.author_name||p.author}</strong><span>{p.rank?'#'+p.rank+' global · ':''}{short(p.worth)} net worth</span></div></button><div className="post-meta"><span>{ago(p.created_at)}</span><span className={'pill '+p.kind}>{p.kind==='trade'?'Trade flex':p.kind==='joke'?'Market humor':'Just chatting'}</span></div></div>{p.content&&<p className="post-content">{p.content}</p>}{p.symbol&&<button className="ticker-tag" onClick={()=>setSearch(p.symbol!)}>${p.symbol}</button>}{trade&&<div className={'trade-card '+(String(trade.side).toUpperCase()==='SELL'?'sell':'')}><div className="trade-label"><TrendingUp size={18}/><span>{trade.side} · {trade.symbol}</span><span className="verified"><Check size={12}/> Verified game receipt</span></div><strong>{money(Number(trade.total))}</strong><div className="trade-details"><span>{trade.shares} shares @ {money(Number(trade.price))}</span>{trade.pnl!=null&&<span>P/L {Number(trade.pnl)>=0?'+':''}{money(Number(trade.pnl))}</span>}</div></div>}{p.image_id&&<div className="post-image"><PrivateImage id={p.image_id} api={api} alt={'Screenshot shared by '+p.author}/></div>}<div className="post-actions"><button className={p.liked?'liked':''} onClick={()=>like(p)}><Heart size={18} fill={p.liked?'currentColor':'none'}/>{p.likes||0}</button><button onClick={()=>openComments(p.id)}><MessageCircle size={18}/>{p.comments||0}<span> replies</span></button>{p.user_id===profile?.id&&<button className="delete" onClick={async()=>{if(!window.confirm('Delete this post and its comments?'))return;try{await api('/api/social',{action:'delete',postId:p.id});await loadFeed();}catch(e:any){setError(e.message);}}}>Delete</button>}</div></article>;})}{next&&<button className="load-more" disabled={loading} onClick={()=>loadFeed(true)}>{loading?'Loading…':'Load more posts'}</button>}</>}</>}
 </main><aside className="rightbar"><section className="profile-card"><div className="profile-banner"><span>✳</span><span>↗</span></div><div className="profile-body"><Avatar name={profile?.name||'RS'} id={profile?.avatar_id} api={api} large/><h2>{profile?.name||'Your next chapter'}</h2><p>{profile?.bio||'Trade. Laugh. Repeat.'}</p><div className="profile-stats"><div><span>TOTAL WEALTH</span><strong>{money(profile?.worth)}</strong></div><div><span>GLOBAL RANK</span><strong>{profile?.rank?'#'+profile.rank:'—'}</strong></div></div>{signed?<><small>Cash: {money(profile?.cash)}</small><button className="outline" onClick={()=>{setBio(profile?.bio||'');setAvatarFile(null);setEdit(true);}}><Camera size={15}/> Edit profile</button><small>Game stats synced {profile?.updated_at?ago(profile.updated_at):'on sign-in'}</small></>:<button className="outline" onClick={()=>setLoginOpen(true)}>Make yourself at home <ArrowUpRight size={14}/></button>}</div></section>
 <section className="leaderboard"><div className="section-title"><span className="icon-circle"><Trophy size={17}/></span><div><h2>The big leagues</h2><p>MarketRush global leaderboard</p></div></div>{board?.top?.length?<ol>{board.top.slice(0,5).map((p:any)=><li key={p.name}><span className={'rank rank-'+p.rank}>{p.rank}</span><button onClick={()=>openProfile(p.name)}><strong>{p.name}</strong><small>{short(p.worth)}</small></button><ArrowUpRight size={15}/></li>)}</ol>:<p className="muted">Sign in to see who’s leading the market.</p>}<div className="leaderboard-foot"><span className="live-dot"/>{board?board.players+' traders · synced every 30s':'Straight from the game'}</div></section>
 <section className="community-note"><Flame size={21}/><h3>Good trades.<br/>Better company.</h3><p>Celebrate the wins. Laugh at the losses. Be kind to the trader on the other side of the screen.</p><div><span>NO REAL MONEY</span><span>JUST THE RUSH ↗</span></div></section></aside></div>
 {loginOpen&&<div className="modal-backdrop"><section className="modal" role="dialog" aria-modal="true" aria-labelledby="login-title"><button className="close" aria-label="Close sign-in" onClick={()=>{setLoginOpen(false);setError('');}}><X size={20}/></button><span className="brand-mark"><ChartNoAxesCombined size={26}/></span><p className="overline">SAME ACCOUNT. NEW CONVERSATION.</p><h2 id="login-title">Welcome to Rush Social.</h2><p>Sign in with your existing MarketRush email and password.</p><form onSubmit={login}><label>Email<input name="email" type="email" required autoComplete="username"/></label><label>Password<input name="password" type="password" required autoComplete="current-password"/></label>{error&&<p className="form-error" role="alert">{error}</p>}<button className="primary" disabled={busy}>{busy?'Connecting…':'Sign in with MarketRush'}<ArrowUpRight size={17}/></button></form><small>Your password goes directly to MarketRush’s authentication service. Your session stays in this tab’s memory.</small></section></div>}
 {edit&&profile&&<div className="modal-backdrop"><section className="modal" role="dialog" aria-modal="true" aria-labelledby="edit-title"><button className="close" aria-label="Close profile editor" onClick={()=>setEdit(false)}><X size={20}/></button><h2 id="edit-title">Make it yours.</h2><p>Your name and game stats come from MarketRush. Your photo and bio are all you.</p><form onSubmit={saveProfile}><Avatar name={profile.name} id={profile.avatar_id} api={api} large/><label>Profile picture<input type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>{const f=e.target.files?.[0];if(f&&validFile(f))setAvatarFile(f);}}/></label>{avatarFile&&<small>{avatarFile.name} · ready to upload</small>}<label>Bio<textarea value={bio} maxLength={160} onChange={e=>setBio(e.target.value)}/></label>{error&&<p className="form-error" role="alert">{error}</p>}<button className="primary" disabled={busy}>{busy?'Saving…':'Save profile'}<Check size={17}/></button></form></section></div>}
 {modalProfile&&<div className="modal-backdrop"><section className="modal profile-modal" role="dialog" aria-modal="true" aria-labelledby="profile-title"><button className="close" aria-label="Close profile" onClick={()=>setModalProfile(null)}><X size={20}/></button><Avatar name={modalProfile.name} id={modalProfile.avatar_id} api={api} large/><h2 id="profile-title">{modalProfile.name}</h2><p>{modalProfile.bio||'MarketRush trader'}</p><div className="profile-stats"><div><span>TOTAL WEALTH</span><strong>{money(modalProfile.worth)}</strong></div><div><span>GLOBAL RANK</span><strong>{modalProfile.rank?'#'+modalProfile.rank:'Unranked'}</strong></div></div><p>Available cash: {money(modalProfile.cash)}</p>{modalProfile.id&&modalProfile.id!==profile?.id&&<button className="primary" onClick={()=>{setDmPeer(modalProfile.id!);setModalProfile(null);setMessagesOpen(true);}}><MessageCircle size={16}/> Message trader</button>}{modalProfile.name===profile?.name&&<button className="outline" onClick={()=>{setModalProfile(null);setBio(profile.bio||'');setAvatarFile(null);setEdit(true);}}><Camera size={15}/> Edit profile</button>}<small>Live game stats · cash + holdings at current prices</small></section></div>}
 {commentsFor&&<div className="modal-backdrop"><section className="modal comments-modal" role="dialog" aria-modal="true" aria-labelledby="replies-title"><button className="close" aria-label="Close replies" onClick={()=>setCommentsFor(null)}><X size={20}/></button><h2 id="replies-title">The conversation</h2><div className="comments-list">{comments.length?comments.map(c=><article key={c.id}><strong>{c.author}</strong><small>{ago(c.created_at)}</small><p>{c.content}</p></article>):<p className="muted">No replies yet. Start the conversation.</p>}</div>{error&&<p className="form-error" role="alert">{error}</p>}<form onSubmit={sendReply}><label>Your reply<textarea value={reply} maxLength={500} required onChange={e=>setReply(e.target.value)}/></label><button className="primary" disabled={busy||!reply.trim()}>Send reply <Send size={16}/></button></form></section></div>}
 {messagesOpen&&profile?.id&&<MessagesPanel api={api} me={profile.id} initialPeer={dmPeer} onClose={()=>setMessagesOpen(false)}/>}
 </div>;
}
